// Refreshes the STATE block in docs/HANDOFF.md from live git/gh data.
// Usage: node scripts/refresh-handoff.mjs
// Requires: git + gh (authenticated). Dependency-free.
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const HANDOFF = join(ROOT, 'docs', 'HANDOFF.md');

function sh(cmd, fallback = 'unknown') {
  try {
    return execSync(cmd, { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return fallback;
  }
}

const branch = sh('git branch --show-current');
const upstream = sh('git rev-parse --abbrev-ref --symbolic-full-name @{u}', 'no-upstream');
const aheadBehind = sh('git rev-list --left-right --count HEAD...@{u}', '?:?');
const lastCommit = sh('git log -1 --format="%h %ad %s" --date=short');
const schemaSrc = (() => {
  try {
    return readFileSync(join(ROOT, 'src', 'db', 'schema.ts'), 'utf8');
  } catch {
    return '';
  }
})();
const schemaMatch = schemaSrc.match(/SCHEMA_VERSION\s*=\s*(\d+)/);
const schema = schemaMatch ? `SCHEMA_VERSION = ${schemaMatch[1]}` : 'SCHEMA_VERSION = ?';
const openPrs = sh(
  `gh pr list --state open --limit 10 --json number,title,headRefName --jq ".[] | [.number, .title, .headRefName] | @tsv"`,
  'gh unavailable',
);
const milestones = sh(
  `gh api repos/chrisdco/incline/milestones --paginate -q ".[] | [.title, .open_issues] | @tsv"`,
  'gh unavailable',
);
const today = new Date().toISOString().slice(0, 10);

const block = [
  '<!-- STATE:START (generated by `node scripts/refresh-handoff.mjs` — do not hand-edit) -->',
  '',
  `- Refreshed: **${today}** · branch: \`${branch}\` → \`${upstream}\` (ahead/behind: ${aheadBehind.replace(/\s+/g, ' / ')})`,
  `- HEAD: \`${lastCommit}\``,
  `- ${schema.trim()}`,
  `- Open PRs: ${openPrs.split('\n').filter(Boolean).map((l) => `\`#${l.replace(/\t/g, ' ')}\``).join(', ') || 'none'}`,
  `- Open issues by milestone: ${milestones.split('\n').filter(Boolean).map((l) => l.replace(/\t/g, ' ')).join(' · ') || 'unknown'}`,
  '',
  '<!-- STATE:END -->',
].join('\n');

let doc = readFileSync(HANDOFF, 'utf8');
const re = /<!-- STATE:START[\s\S]*?<!-- STATE:END -->/;
if (!re.test(doc)) {
  console.error('HANDOFF.md has no STATE block markers — aborting.');
  process.exit(1);
}
doc = doc.replace(re, block);
writeFileSync(HANDOFF, doc);
console.log(`HANDOFF.md STATE refreshed (${today}, ${branch}).`);
